export const TRENDING_CAFES_COUNT = 3;
export const TRENDING_CAFES_COLUMNS = 1;
export const CAFE_GRID_ITEMS_PER_PAGE = 8;
export const SMALL_CARD_IMAGE_HEIGHT = 120;
export const LARGE_CARD_IMAGE_HEIGHT = 200;

